/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazSO;

import Main.Functions;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class interfazSoMain extends javax.swing.JFrame {

    /**
     * Creates new form interfazSoMain
     */
    
    boolean simulation = false; // Detecta si la simulacion esta en movimiento o detenida.
    Functions fun = new Functions();
    
    public interfazSoMain() {
        initComponents();
        this.setResizable(false); // No se puede cambiar de tamaño la ventana
        this.setLocationRelativeTo(null);  // Se abre en el centro de toda la pantalla 
        ImageIcon imageTitle = new ImageIcon(getClass().getResource("/interfazSOComponents/ikea_logo_icon.png")); 
        Icon fondoTitle = new ImageIcon(imageTitle.getImage().getScaledInstance(300, 200, Image.SCALE_DEFAULT));   // Ajustar el tamaño de la imagen superior
        logo.setIcon(fondoTitle);
        this.repaint();
        setIconImage(new ImageIcon(getClass().getResource("/interfazSOComponents/logo.png")).getImage());         // Icono de la barra inferior
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        registerinformation = new javax.swing.JPanel();
        infoPanel = new javax.swing.JPanel();
        bossInformed = new javax.swing.JLabel();
        maganerInformer = new javax.swing.JLabel();
        BossInfo = new javax.swing.JLabel();
        ManagerInfo = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        barBottom = new javax.swing.JPanel();
        tRemaing = new javax.swing.JLabel();
        domsdayClock = new javax.swing.JTextField();
        readyPAHL = new javax.swing.JPanel();
        PAHLCount = new javax.swing.JTextField();
        PAHL = new javax.swing.JLabel();
        time = new javax.swing.JPanel();
        timer = new javax.swing.JTextField();
        todayIs = new javax.swing.JLabel();
        minizar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        registerProducers = new javax.swing.JPanel();
        produceScrew = new javax.swing.JPanel();
        screwCount = new javax.swing.JTextField();
        screwName = new javax.swing.JLabel();
        produceTable = new javax.swing.JPanel();
        tableCount = new javax.swing.JTextField();
        tableName = new javax.swing.JLabel();
        producePaw = new javax.swing.JPanel();
        pawCount = new javax.swing.JTextField();
        pawName = new javax.swing.JLabel();
        assemblerData = new javax.swing.JPanel();
        assemblerCount = new javax.swing.JTextField();
        assemblerName = new javax.swing.JLabel();
        productor = new java.awt.Label();
        assembler = new java.awt.Label();
        addPaw = new javax.swing.JButton();
        addTable = new javax.swing.JButton();
        addScrew = new javax.swing.JButton();
        addAsem = new javax.swing.JButton();
        popAsem = new javax.swing.JButton();
        popScrew = new javax.swing.JButton();
        popTable = new javax.swing.JButton();
        popPaw = new javax.swing.JButton();
        registersProducts1 = new javax.swing.JPanel();
        produce1 = new java.awt.Label();
        productPaw1 = new javax.swing.JPanel();
        pPawCount1 = new javax.swing.JTextField();
        pPaw1 = new javax.swing.JLabel();
        productScrew1 = new javax.swing.JPanel();
        pScrewCount1 = new javax.swing.JTextField();
        pScrew1 = new javax.swing.JLabel();
        productTable1 = new javax.swing.JPanel();
        pTableCount1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        simulate = new javax.swing.JToggleButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOIkea");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(0, 0, 51));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerinformation.setBackground(new java.awt.Color(255, 204, 102));
        registerinformation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerinformation.setForeground(new java.awt.Color(51, 51, 51));
        registerinformation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infoPanel.setBackground(new java.awt.Color(204, 204, 204));
        infoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        infoPanel.setForeground(new java.awt.Color(0, 0, 0));

        bossInformed.setBackground(new java.awt.Color(204, 204, 204));
        bossInformed.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bossInformed.setForeground(new java.awt.Color(0, 0, 0));
        bossInformed.setText("El Jefe:");
        bossInformed.setToolTipText("");

        maganerInformer.setBackground(new java.awt.Color(204, 204, 204));
        maganerInformer.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        maganerInformer.setForeground(new java.awt.Color(0, 0, 0));
        maganerInformer.setText("El gerente:");

        BossInfo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BossInfo.setForeground(new java.awt.Color(0, 0, 0));
        BossInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BossInfo.setText("Dumiendo...");

        ManagerInfo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ManagerInfo.setForeground(new java.awt.Color(0, 0, 0));
        ManagerInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManagerInfo.setText("Dumiendo...");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(maganerInformer, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bossInformed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BossInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ManagerInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bossInformed, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(BossInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maganerInformer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ManagerInfo)
                .addContainerGap())
        );

        registerinformation.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 210, 140));

        Info.setBackground(new java.awt.Color(0, 0, 0));
        Info.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        Info.setForeground(new java.awt.Color(0, 0, 0));
        Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Info.setText("Informacion:");
        Info.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerinformation.add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 150, 20));

        reset.setFont(new java.awt.Font("RomanC", 1, 18)); // NOI18N
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/reset .png"))); // NOI18N
        reset.setBorderPainted(false);
        reset.setContentAreaFilled(false);
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/resetPisado.png"))); // NOI18N
        reset.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        reset.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        registerinformation.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 130, -1));

        jPanelPrincipal.add(registerinformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 250, 370));

        barBottom.setBackground(new java.awt.Color(153, 204, 255));
        barBottom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tRemaing.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        tRemaing.setText("Tiempo restante: ");

        domsdayClock.setEditable(false);
        domsdayClock.setBackground(new java.awt.Color(153, 255, 255));
        domsdayClock.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        domsdayClock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        domsdayClock.setText("0");

        readyPAHL.setBackground(new java.awt.Color(0, 204, 153));
        readyPAHL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        PAHLCount.setEditable(false);
        PAHLCount.setBackground(new java.awt.Color(0, 255, 153));
        PAHLCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        PAHLCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PAHLCount.setText("0");

        PAHL.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        PAHL.setText("Escritorios: ");

        javax.swing.GroupLayout readyPAHLLayout = new javax.swing.GroupLayout(readyPAHL);
        readyPAHL.setLayout(readyPAHLLayout);
        readyPAHLLayout.setHorizontalGroup(
            readyPAHLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readyPAHLLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(PAHL, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(PAHLCount, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        readyPAHLLayout.setVerticalGroup(
            readyPAHLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readyPAHLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(readyPAHLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PAHLCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PAHL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        time.setBackground(new java.awt.Color(0, 204, 153));
        time.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        timer.setEditable(false);
        timer.setBackground(new java.awt.Color(0, 255, 153));
        timer.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        timer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        timer.setText("0");

        todayIs.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        todayIs.setText("Fecha: ");

        javax.swing.GroupLayout timeLayout = new javax.swing.GroupLayout(time);
        time.setLayout(timeLayout);
        timeLayout.setHorizontalGroup(
            timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(todayIs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        timeLayout.setVerticalGroup(
            timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(todayIs)
                    .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout barBottomLayout = new javax.swing.GroupLayout(barBottom);
        barBottom.setLayout(barBottomLayout);
        barBottomLayout.setHorizontalGroup(
            barBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barBottomLayout.createSequentialGroup()
                .addComponent(readyPAHL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tRemaing, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(domsdayClock, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barBottomLayout.setVerticalGroup(
            barBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tRemaing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(domsdayClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(barBottomLayout.createSequentialGroup()
                .addComponent(readyPAHL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(barBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 800, 50));

        minizar.setBackground(new java.awt.Color(255, 204, 0));
        minizar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        minizar.setText("_");
        minizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minizarActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(minizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 40, -1));

        cerrar.setBackground(new java.awt.Color(204, 0, 0));
        cerrar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("X");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 40, -1));

        registerProducers.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registerProducers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        produceScrew.setBackground(new java.awt.Color(255, 255, 255));
        produceScrew.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        screwCount.setEditable(false);
        screwCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        screwCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        screwCount.setText("1");

        screwName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        screwName.setText("Tornillos:");
        screwName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout produceScrewLayout = new javax.swing.GroupLayout(produceScrew);
        produceScrew.setLayout(produceScrewLayout);
        produceScrewLayout.setHorizontalGroup(
            produceScrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produceScrewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screwName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(screwCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        produceScrewLayout.setVerticalGroup(
            produceScrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produceScrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(screwCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(screwName))
        );

        registerProducers.add(produceScrew, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 200, -1));

        produceTable.setBackground(new java.awt.Color(255, 255, 255));
        produceTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tableCount.setEditable(false);
        tableCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        tableCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tableCount.setText("1");

        tableName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tableName.setText("Tablas:");
        tableName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout produceTableLayout = new javax.swing.GroupLayout(produceTable);
        produceTable.setLayout(produceTableLayout);
        produceTableLayout.setHorizontalGroup(
            produceTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produceTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(tableCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        produceTableLayout.setVerticalGroup(
            produceTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produceTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tableCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(tableName))
        );

        registerProducers.add(produceTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 200, -1));

        producePaw.setBackground(new java.awt.Color(255, 255, 255));
        producePaw.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pawCount.setEditable(false);
        pawCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        pawCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pawCount.setText("1");

        pawName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pawName.setText("Patas:");
        pawName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout producePawLayout = new javax.swing.GroupLayout(producePaw);
        producePaw.setLayout(producePawLayout);
        producePawLayout.setHorizontalGroup(
            producePawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, producePawLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pawName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pawCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        producePawLayout.setVerticalGroup(
            producePawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producePawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(pawCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(pawName))
        );

        registerProducers.add(producePaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 200, 36));

        assemblerData.setBackground(new java.awt.Color(255, 255, 255));
        assemblerData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        assemblerCount.setEditable(false);
        assemblerCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        assemblerCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        assemblerCount.setText("1");

        assemblerName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        assemblerName.setText("Trabajando:");
        assemblerName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout assemblerDataLayout = new javax.swing.GroupLayout(assemblerData);
        assemblerData.setLayout(assemblerDataLayout);
        assemblerDataLayout.setHorizontalGroup(
            assemblerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assemblerDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assemblerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(assemblerCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        assemblerDataLayout.setVerticalGroup(
            assemblerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assemblerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(assemblerCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(assemblerName))
        );

        registerProducers.add(assemblerData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 200, -1));

        productor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        productor.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        productor.setText("Productores:");
        registerProducers.add(productor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        assembler.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        assembler.setText("Ensambladores:");
        registerProducers.add(assembler, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        addPaw.setText(">>");
        addPaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPawActionPerformed(evt);
            }
        });
        registerProducers.add(addPaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 45, 34));

        addTable.setText(">>");
        addTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTableActionPerformed(evt);
            }
        });
        registerProducers.add(addTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 45, 34));

        addScrew.setText(">>");
        addScrew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addScrewActionPerformed(evt);
            }
        });
        registerProducers.add(addScrew, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 45, 34));

        addAsem.setText(">>");
        addAsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAsemActionPerformed(evt);
            }
        });
        registerProducers.add(addAsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 45, 34));

        popAsem.setText("<<");
        popAsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popAsemActionPerformed(evt);
            }
        });
        registerProducers.add(popAsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 45, 34));

        popScrew.setText("<<");
        popScrew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popScrewActionPerformed(evt);
            }
        });
        registerProducers.add(popScrew, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 45, 34));

        popTable.setText("<<");
        popTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popTableActionPerformed(evt);
            }
        });
        registerProducers.add(popTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 45, 34));

        popPaw.setText("<<");
        popPaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popPawActionPerformed(evt);
            }
        });
        registerProducers.add(popPaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 45, 34));

        jPanelPrincipal.add(registerProducers, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 320, 370));

        registersProducts1.setBackground(new java.awt.Color(255, 204, 102));
        registersProducts1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registersProducts1.setForeground(new java.awt.Color(51, 51, 51));
        registersProducts1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        produce1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        produce1.setText("Productos:");
        registersProducts1.add(produce1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        productPaw1.setBackground(new java.awt.Color(255, 255, 255));
        productPaw1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pPawCount1.setEditable(false);
        pPawCount1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        pPawCount1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pPawCount1.setText("0");

        pPaw1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pPaw1.setText("Patas:");
        pPaw1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout productPaw1Layout = new javax.swing.GroupLayout(productPaw1);
        productPaw1.setLayout(productPaw1Layout);
        productPaw1Layout.setHorizontalGroup(
            productPaw1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPaw1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPaw1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(pPawCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        productPaw1Layout.setVerticalGroup(
            productPaw1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPaw1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(pPawCount1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(pPaw1))
        );

        registersProducts1.add(productPaw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, -1));

        productScrew1.setBackground(new java.awt.Color(255, 255, 255));
        productScrew1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pScrewCount1.setEditable(false);
        pScrewCount1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        pScrewCount1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pScrewCount1.setText("0");

        pScrew1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pScrew1.setText("Tornillos:");
        pScrew1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout productScrew1Layout = new javax.swing.GroupLayout(productScrew1);
        productScrew1.setLayout(productScrew1Layout);
        productScrew1Layout.setHorizontalGroup(
            productScrew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productScrew1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pScrew1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(pScrewCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        productScrew1Layout.setVerticalGroup(
            productScrew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productScrew1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(pScrewCount1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(pScrew1))
        );

        registersProducts1.add(productScrew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, -1));

        productTable1.setBackground(new java.awt.Color(255, 255, 255));
        productTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pTableCount1.setEditable(false);
        pTableCount1.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        pTableCount1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pTableCount1.setText("0");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel12.setText("Tablas:");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout productTable1Layout = new javax.swing.GroupLayout(productTable1);
        productTable1.setLayout(productTable1Layout);
        productTable1Layout.setHorizontalGroup(
            productTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productTable1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(pTableCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        productTable1Layout.setVerticalGroup(
            productTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(pTableCount1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(jLabel12))
        );

        registersProducts1.add(productTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 210, -1));

        simulate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/stop.png"))); // NOI18N
        simulate.setBorderPainted(false);
        simulate.setContentAreaFilled(false);
        simulate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulate.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/iniciarPisado.png"))); // NOI18N
        simulate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/stopPisado.png"))); // NOI18N
        simulate.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/iniciarPisado.png"))); // NOI18N
        simulate.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/iniciarEjecucion.png"))); // NOI18N
        simulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateActionPerformed(evt);
            }
        });
        registersProducts1.add(simulate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 138, 138));

        jPanelPrincipal.add(registersProducts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 370));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/ikea_logo_icon.png"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelPrincipal.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, 40));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    // ==============================================================================================================
    //      >> Boton de reinicio:
    // ==============================================================================================================
    
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        
        if(simulation){
            System.out.println("Reinicio bloqueado, Por favor apagar simulación primero.");
            JOptionPane.showMessageDialog(null, "Porfavor, antes de reiniciar, detenga la simulación.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            System.out.println("Protocolo de reinicio de sistema activado...");
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea reiniciar la simulacion?", "Reinicio de sistema.", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == resp){
                System.out.println("Reinicio confirmado...");
            }else{
                System.out.println("Reinicio cancelado.");
            }
        }
          
    }//GEN-LAST:event_resetActionPerformed
        
    // ==============================================================================================================
    //      >> Botones de cerrar y reducir ventana:
    // ==============================================================================================================
    
    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        if(simulation){
            System.out.println("Por favor, detenga la simulacion antes de cerrar la aplicacion.");
            JOptionPane.showMessageDialog(null, "Por favor, detenga la simulacion para poder de cerrar la aplicacion.", "Sistema de seguridad.", JOptionPane.ERROR_MESSAGE);
        }else{
            System.out.println(" >> LA APLICACION SE CERRARA.");
            System.exit(0);
            System.out.println("Ejecucion finalizada");
            JOptionPane.showMessageDialog(null, "El sistema IKEA PAHL a finalizado su ejecucion con exito", "Sistema principal.", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }

    }//GEN-LAST:event_cerrarActionPerformed

    private void minizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minizarActionPerformed
        // TODO add your handling code here:
        System.out.println("Ventana minimizada.");
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minizarActionPerformed
    // ==============================================================================================================
    //      >> Botones de Contratar y Despedir:
    // ==============================================================================================================
    
    private void addPawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPawActionPerformed
        // TODO add your handling code here:
        pawCount.setText(fun.contratar(4, pawCount.getText(), "patas"));
    }//GEN-LAST:event_addPawActionPerformed

    private void addTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTableActionPerformed
        // TODO add your handling code here:
        tableCount.setText(fun.contratar(4, tableCount.getText(), "tablas"));
    }//GEN-LAST:event_addTableActionPerformed

    private void addScrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addScrewActionPerformed
        // TODO add your handling code here:
        screwCount.setText(fun.contratar(3, screwCount.getText(), "tornillos"));
    }//GEN-LAST:event_addScrewActionPerformed

    private void addAsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAsemActionPerformed
        // TODO add your handling code here:
        assemblerCount.setText(fun.contratar(3, assemblerCount.getText(), "ensambladores"));
    }//GEN-LAST:event_addAsemActionPerformed

    private void popAsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popAsemActionPerformed
        // TODO add your handling code here:
        assemblerCount.setText(fun.despedir(assemblerCount.getText(), "ensambladores"));
    }//GEN-LAST:event_popAsemActionPerformed

    private void popScrewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popScrewActionPerformed
        // TODO add your handling code here:
        screwCount.setText(fun.despedir(screwCount.getText(), "tornillos"));
    }//GEN-LAST:event_popScrewActionPerformed

    private void popTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popTableActionPerformed
        // TODO add your handling code here:
        tableCount.setText(fun.despedir(tableCount.getText(), "tablas"));
    }//GEN-LAST:event_popTableActionPerformed

    private void popPawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popPawActionPerformed
        // TODO add your handling code here:
        pawCount.setText(fun.despedir(pawCount.getText(), "patas"));
    }//GEN-LAST:event_popPawActionPerformed

    // ==============================================================================================================
    //      >> Boton de Simulacion:
    // ==============================================================================================================
    
    private void simulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateActionPerformed
        // TODO add your handling code here:
        if(simulate.isSelected()){ // Si la simulacion se esta ejecutando, no puedes cerrar ni reiniciar los valores, por seguridad
            System.out.println("¡El simulador se ha activado!");
            simulation = true;  // Avisa al sistema que la simulacion esta en movimiento
        }else{
            System.out.println("¡La simulacion se ha desactivado!");
            simulation = false; // Avisa al sistema que la simulacion se detuvo
        }
    
    }//GEN-LAST:event_simulateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazSoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazSoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazSoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazSoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazSoMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BossInfo;
    private javax.swing.JLabel Info;
    private javax.swing.JLabel ManagerInfo;
    private javax.swing.JLabel PAHL;
    private javax.swing.JTextField PAHLCount;
    private javax.swing.JButton addAsem;
    private javax.swing.JButton addPaw;
    private javax.swing.JButton addScrew;
    private javax.swing.JButton addTable;
    private java.awt.Label assembler;
    private javax.swing.JTextField assemblerCount;
    private javax.swing.JPanel assemblerData;
    private javax.swing.JLabel assemblerName;
    private javax.swing.JPanel barBottom;
    private javax.swing.JLabel bossInformed;
    private javax.swing.JButton cerrar;
    private javax.swing.JTextField domsdayClock;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel maganerInformer;
    private javax.swing.JButton minizar;
    private javax.swing.JLabel pPaw1;
    private javax.swing.JTextField pPawCount1;
    private javax.swing.JLabel pScrew1;
    private javax.swing.JTextField pScrewCount1;
    private javax.swing.JTextField pTableCount1;
    private javax.swing.JTextField pawCount;
    private javax.swing.JLabel pawName;
    private javax.swing.JButton popAsem;
    private javax.swing.JButton popPaw;
    private javax.swing.JButton popScrew;
    private javax.swing.JButton popTable;
    private java.awt.Label produce1;
    private javax.swing.JPanel producePaw;
    private javax.swing.JPanel produceScrew;
    private javax.swing.JPanel produceTable;
    private javax.swing.JPanel productPaw1;
    private javax.swing.JPanel productScrew1;
    private javax.swing.JPanel productTable1;
    private java.awt.Label productor;
    private javax.swing.JPanel readyPAHL;
    private javax.swing.JPanel registerProducers;
    private javax.swing.JPanel registerinformation;
    private javax.swing.JPanel registersProducts1;
    private javax.swing.JButton reset;
    private javax.swing.JTextField screwCount;
    private javax.swing.JLabel screwName;
    private javax.swing.JToggleButton simulate;
    private javax.swing.JLabel tRemaing;
    private javax.swing.JTextField tableCount;
    private javax.swing.JLabel tableName;
    private javax.swing.JPanel time;
    private javax.swing.JTextField timer;
    private javax.swing.JLabel todayIs;
    // End of variables declaration//GEN-END:variables
}
