/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazSO;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class interfazSoMain extends javax.swing.JFrame {

    /**
     * Creates new form interfazSoMain
     */
    
    boolean simulation = false;
    
    public interfazSoMain() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/interfazSOComponents/logo.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        registers = new javax.swing.JPanel();
        produce = new java.awt.Label();
        assembler = new java.awt.Label();
        productor = new java.awt.Label();
        produceScrew = new javax.swing.JPanel();
        screwCount = new javax.swing.JTextField();
        screwName = new javax.swing.JLabel();
        produceTable = new javax.swing.JPanel();
        tableCount = new javax.swing.JTextField();
        tableName = new javax.swing.JLabel();
        producePaw = new javax.swing.JPanel();
        pawCount = new javax.swing.JTextField();
        pawName = new javax.swing.JLabel();
        productPaw = new javax.swing.JPanel();
        pPawCount = new javax.swing.JTextField();
        pPaw = new javax.swing.JLabel();
        productScrew = new javax.swing.JPanel();
        pScrewCount = new javax.swing.JTextField();
        pScrew = new javax.swing.JLabel();
        productTable = new javax.swing.JPanel();
        pTableCount = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        assemblerData = new javax.swing.JPanel();
        assemblerCount = new javax.swing.JTextField();
        assemblerName = new javax.swing.JLabel();
        simulate = new javax.swing.JToggleButton();
        barBottom = new javax.swing.JPanel();
        tRemaing = new javax.swing.JLabel();
        domsdayClock = new javax.swing.JTextField();
        readyPAHL = new javax.swing.JPanel();
        PAHLCount = new javax.swing.JTextField();
        PAHL = new javax.swing.JLabel();
        time = new javax.swing.JPanel();
        timer = new javax.swing.JTextField();
        todayIs = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        bossInformed = new javax.swing.JLabel();
        maganerInformer = new javax.swing.JLabel();
        Info = new javax.swing.JLabel();
        minizar = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SOIkea");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        jPanelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registers.setBackground(new java.awt.Color(255, 204, 102));
        registers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        registers.setForeground(new java.awt.Color(51, 51, 51));
        registers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        produce.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        produce.setText("Productos:");
        registers.add(produce, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        assembler.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        assembler.setText("Ensambladores:");
        registers.add(assembler, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        productor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        productor.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        productor.setText("Productores:");
        registers.add(productor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        produceScrew.setBackground(new java.awt.Color(255, 255, 255));
        produceScrew.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        screwCount.setEditable(false);
        screwCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        screwCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        screwCount.setText("0");

        screwName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        screwName.setForeground(new java.awt.Color(0, 0, 0));
        screwName.setText("Tornillos:");
        screwName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout produceScrewLayout = new javax.swing.GroupLayout(produceScrew);
        produceScrew.setLayout(produceScrewLayout);
        produceScrewLayout.setHorizontalGroup(
            produceScrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produceScrewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(screwName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(screwCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        produceScrewLayout.setVerticalGroup(
            produceScrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produceScrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(screwCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(screwName))
        );

        registers.add(produceScrew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, -1));

        produceTable.setBackground(new java.awt.Color(255, 255, 255));
        produceTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tableCount.setEditable(false);
        tableCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        tableCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tableCount.setText("0");

        tableName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tableName.setForeground(new java.awt.Color(0, 0, 0));
        tableName.setText("Tablas:");
        tableName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout produceTableLayout = new javax.swing.GroupLayout(produceTable);
        produceTable.setLayout(produceTableLayout);
        produceTableLayout.setHorizontalGroup(
            produceTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, produceTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(tableCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        produceTableLayout.setVerticalGroup(
            produceTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(produceTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tableCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(tableName))
        );

        registers.add(produceTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 190, -1));

        producePaw.setBackground(new java.awt.Color(255, 255, 255));
        producePaw.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pawCount.setEditable(false);
        pawCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        pawCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pawCount.setText("0");

        pawName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pawName.setForeground(new java.awt.Color(0, 0, 0));
        pawName.setText("Patas:");
        pawName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout producePawLayout = new javax.swing.GroupLayout(producePaw);
        producePaw.setLayout(producePawLayout);
        producePawLayout.setHorizontalGroup(
            producePawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, producePawLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pawName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(pawCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        producePawLayout.setVerticalGroup(
            producePawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(producePawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(pawCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(pawName))
        );

        registers.add(producePaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, -1));

        productPaw.setBackground(new java.awt.Color(255, 255, 255));
        productPaw.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pPawCount.setEditable(false);
        pPawCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        pPawCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pPawCount.setText("0");

        pPaw.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pPaw.setForeground(new java.awt.Color(0, 0, 0));
        pPaw.setText("Patas:");
        pPaw.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout productPawLayout = new javax.swing.GroupLayout(productPaw);
        productPaw.setLayout(productPawLayout);
        productPawLayout.setHorizontalGroup(
            productPawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productPawLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pPaw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(pPawCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        productPawLayout.setVerticalGroup(
            productPawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(pPawCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(pPaw))
        );

        registers.add(productPaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 190, -1));

        productScrew.setBackground(new java.awt.Color(255, 255, 255));
        productScrew.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pScrewCount.setEditable(false);
        pScrewCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        pScrewCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pScrewCount.setText("0");

        pScrew.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        pScrew.setForeground(new java.awt.Color(0, 0, 0));
        pScrew.setText("Tornillos:");
        pScrew.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout productScrewLayout = new javax.swing.GroupLayout(productScrew);
        productScrew.setLayout(productScrewLayout);
        productScrewLayout.setHorizontalGroup(
            productScrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productScrewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pScrew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(pScrewCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        productScrewLayout.setVerticalGroup(
            productScrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productScrewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(pScrewCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(pScrew))
        );

        registers.add(productScrew, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, -1));

        productTable.setBackground(new java.awt.Color(255, 255, 255));
        productTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pTableCount.setEditable(false);
        pTableCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        pTableCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        pTableCount.setText("0");

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tablas:");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout productTableLayout = new javax.swing.GroupLayout(productTable);
        productTable.setLayout(productTableLayout);
        productTableLayout.setHorizontalGroup(
            productTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productTableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(pTableCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        productTableLayout.setVerticalGroup(
            productTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(pTableCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        registers.add(productTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 190, -1));

        assemblerData.setBackground(new java.awt.Color(255, 255, 255));
        assemblerData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        assemblerCount.setEditable(false);
        assemblerCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        assemblerCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        assemblerCount.setText("0");

        assemblerName.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        assemblerName.setForeground(new java.awt.Color(0, 0, 0));
        assemblerName.setText("Trabajando:");
        assemblerName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout assemblerDataLayout = new javax.swing.GroupLayout(assemblerData);
        assemblerData.setLayout(assemblerDataLayout);
        assemblerDataLayout.setHorizontalGroup(
            assemblerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, assemblerDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(assemblerName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(assemblerCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        assemblerDataLayout.setVerticalGroup(
            assemblerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(assemblerDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(assemblerCount, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(assemblerName))
        );

        registers.add(assemblerData, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 190, -1));

        simulate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/stop.png"))); // NOI18N
        simulate.setBorderPainted(false);
        simulate.setContentAreaFilled(false);
        simulate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        simulate.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/iniciarPisado.png"))); // NOI18N
        simulate.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/stopPisado.png"))); // NOI18N
        simulate.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/iniciarPisado.png"))); // NOI18N
        simulate.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/iniciarEjecucion.png"))); // NOI18N
        simulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simulateActionPerformed(evt);
            }
        });
        registers.add(simulate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 138, 138));

        jPanelPrincipal.add(registers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 630));

        barBottom.setBackground(new java.awt.Color(153, 204, 255));
        barBottom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tRemaing.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        tRemaing.setForeground(new java.awt.Color(0, 0, 0));
        tRemaing.setText("Tiempo restante: ");

        domsdayClock.setEditable(false);
        domsdayClock.setBackground(new java.awt.Color(153, 255, 255));
        domsdayClock.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        domsdayClock.setForeground(new java.awt.Color(0, 0, 0));
        domsdayClock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        domsdayClock.setText("0");

        readyPAHL.setBackground(new java.awt.Color(0, 204, 153));
        readyPAHL.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        PAHLCount.setEditable(false);
        PAHLCount.setBackground(new java.awt.Color(0, 255, 153));
        PAHLCount.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        PAHLCount.setForeground(new java.awt.Color(0, 0, 0));
        PAHLCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        PAHLCount.setText("0");

        PAHL.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        PAHL.setForeground(new java.awt.Color(0, 0, 0));
        PAHL.setText("Escritorios: ");

        javax.swing.GroupLayout readyPAHLLayout = new javax.swing.GroupLayout(readyPAHL);
        readyPAHL.setLayout(readyPAHLLayout);
        readyPAHLLayout.setHorizontalGroup(
            readyPAHLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, readyPAHLLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(PAHL, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(PAHLCount, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        readyPAHLLayout.setVerticalGroup(
            readyPAHLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(readyPAHLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(readyPAHLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PAHLCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PAHL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        time.setBackground(new java.awt.Color(0, 204, 153));
        time.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        timer.setEditable(false);
        timer.setBackground(new java.awt.Color(0, 255, 153));
        timer.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 12)); // NOI18N
        timer.setForeground(new java.awt.Color(0, 0, 0));
        timer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        timer.setText("0");

        todayIs.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        todayIs.setForeground(new java.awt.Color(0, 0, 0));
        todayIs.setText("Fecha: ");

        javax.swing.GroupLayout timeLayout = new javax.swing.GroupLayout(time);
        time.setLayout(timeLayout);
        timeLayout.setHorizontalGroup(
            timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(todayIs, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        timeLayout.setVerticalGroup(
            timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(timeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(todayIs)
                    .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout barBottomLayout = new javax.swing.GroupLayout(barBottom);
        barBottom.setLayout(barBottomLayout);
        barBottomLayout.setHorizontalGroup(
            barBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barBottomLayout.createSequentialGroup()
                .addComponent(readyPAHL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tRemaing, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(domsdayClock, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        barBottomLayout.setVerticalGroup(
            barBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tRemaing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(domsdayClock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(readyPAHL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(time, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanelPrincipal.add(barBottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 590, 600, 50));

        reset.setFont(new java.awt.Font("RomanC", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 0));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/reset .png"))); // NOI18N
        reset.setText("Reinicio");
        reset.setBorderPainted(false);
        reset.setContentAreaFilled(false);
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/resetPisado.png"))); // NOI18N
        reset.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        reset.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 220, 130, -1));

        add.setFont(new java.awt.Font("RomanC", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(0, 0, 0));
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/add.png"))); // NOI18N
        add.setText("Agregar");
        add.setBorderPainted(false);
        add.setContentAreaFilled(false);
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/addPisado.png"))); // NOI18N
        add.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 130, 160));

        delete.setFont(new java.awt.Font("RomanC", 1, 18)); // NOI18N
        delete.setForeground(new java.awt.Color(0, 0, 0));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/delete.png"))); // NOI18N
        delete.setText("Eliminar");
        delete.setBorderPainted(false);
        delete.setContentAreaFilled(false);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        delete.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/deletePisado.png"))); // NOI18N
        delete.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        delete.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 130, -1));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/interfazSOComponents/ikea_logo_icon.png"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelPrincipal.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 460, 150));

        infoPanel.setBackground(new java.awt.Color(204, 204, 204));
        infoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        infoPanel.setForeground(new java.awt.Color(153, 153, 153));

        bossInformed.setFont(new java.awt.Font("RomanC", 1, 14)); // NOI18N
        bossInformed.setForeground(new java.awt.Color(0, 0, 0));
        bossInformed.setText("El jefe esta durmiendo");

        maganerInformer.setFont(new java.awt.Font("RomanC", 1, 14)); // NOI18N
        maganerInformer.setForeground(new java.awt.Color(0, 0, 0));
        maganerInformer.setText("El gerente esta durmiendo");

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addComponent(maganerInformer)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                        .addComponent(bossInformed)
                        .addGap(114, 114, 114))))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(bossInformed)
                .addGap(26, 26, 26)
                .addComponent(maganerInformer)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelPrincipal.add(infoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, 450, -1));

        Info.setBackground(new java.awt.Color(0, 0, 0));
        Info.setFont(new java.awt.Font("RomanC", 1, 16)); // NOI18N
        Info.setForeground(new java.awt.Color(0, 0, 0));
        Info.setText("Informacion:");
        jPanelPrincipal.add(Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 150, 20));

        minizar.setBackground(new java.awt.Color(255, 204, 0));
        minizar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        minizar.setForeground(new java.awt.Color(0, 0, 0));
        minizar.setText("_");
        minizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minizarActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(minizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 40, -1));

        cerrar.setBackground(new java.awt.Color(204, 0, 0));
        cerrar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        cerrar.setForeground(new java.awt.Color(255, 255, 255));
        cerrar.setText("X");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 40, -1));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
            
    private void simulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simulateActionPerformed
        // TODO add your handling code here:
        if(simulate.isSelected()){
            System.out.println("¡El simulador se ha activado!");
            simulation = true;
        }else{
            System.out.println("¡La simulacion se ha desactivado!");
            simulation = false;
        }
    }//GEN-LAST:event_simulateActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        System.out.println("Agregar: ");
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        System.out.println("Eliminar:");
    }//GEN-LAST:event_deleteActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        
        if(simulation){
            System.out.println("Reinicio bloqueado, Por favor apagar simulación primero.");
            JOptionPane.showMessageDialog(null, "Porfavor, antes de reiniciar, detenga la simulación.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }else{
            System.out.println("Protocolo de reinicio de sistema activado...");
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea reiniciar la simulacion?", "Reinicio de sistema.", JOptionPane.YES_NO_OPTION);
            if (JOptionPane.YES_OPTION == resp){
                System.out.println("Reinicio confirmado...");
            }else{
                System.out.println("Reinicio cancelado.");
            }
        }
          
    }//GEN-LAST:event_resetActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        if(simulation){
            System.out.println("Por favor, detenga la simulacion antes de cerrar la aplicacion.");
            JOptionPane.showMessageDialog(null, "Por favor, detenga la simulacion para poder de cerrar la aplicacion.", "Sistema de seguridad.", JOptionPane.ERROR_MESSAGE);
        }else{
            System.out.println(" >> LA APLICACION SE CERRARA.");
            System.exit(0);
            System.out.println("Ejecucion finalizada");
            JOptionPane.showMessageDialog(null, "El sistema IKEA PAHL a finalizado su ejecucion con exito", "Sistema principal.", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }

    }//GEN-LAST:event_cerrarActionPerformed

    private void minizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minizarActionPerformed
        // TODO add your handling code here:
        System.out.println("Ventana minimizada.");
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazSoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazSoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazSoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazSoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazSoMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Info;
    private javax.swing.JLabel PAHL;
    private javax.swing.JTextField PAHLCount;
    private javax.swing.JButton add;
    private java.awt.Label assembler;
    private javax.swing.JTextField assemblerCount;
    private javax.swing.JPanel assemblerData;
    private javax.swing.JLabel assemblerName;
    private javax.swing.JPanel barBottom;
    private javax.swing.JLabel bossInformed;
    private javax.swing.JButton cerrar;
    private javax.swing.JButton delete;
    private javax.swing.JTextField domsdayClock;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel maganerInformer;
    private javax.swing.JButton minizar;
    private javax.swing.JLabel pPaw;
    private javax.swing.JTextField pPawCount;
    private javax.swing.JLabel pScrew;
    private javax.swing.JTextField pScrewCount;
    private javax.swing.JTextField pTableCount;
    private javax.swing.JTextField pawCount;
    private javax.swing.JLabel pawName;
    private java.awt.Label produce;
    private javax.swing.JPanel producePaw;
    private javax.swing.JPanel produceScrew;
    private javax.swing.JPanel produceTable;
    private javax.swing.JPanel productPaw;
    private javax.swing.JPanel productScrew;
    private javax.swing.JPanel productTable;
    private java.awt.Label productor;
    private javax.swing.JPanel readyPAHL;
    private javax.swing.JPanel registers;
    private javax.swing.JButton reset;
    private javax.swing.JTextField screwCount;
    private javax.swing.JLabel screwName;
    private javax.swing.JToggleButton simulate;
    private javax.swing.JLabel tRemaing;
    private javax.swing.JTextField tableCount;
    private javax.swing.JLabel tableName;
    private javax.swing.JPanel time;
    private javax.swing.JTextField timer;
    private javax.swing.JLabel todayIs;
    // End of variables declaration//GEN-END:variables
}
